version: "3"
services:
    python:
        image: python:3.8-alpine
        volumes:
            - ./src:/app
            - "$PWD/flag:/fl0g:ro"
        restart: always
        environment: 
            TZ: Asia/Shanghai
        ports:
            - "9999:8080"
        command: python3 /app/main.py
        networks:
            - default

networks:
    # 配置docker network
    default: 